version: 2.1

executors:
  docker-publisher:
    docker:
      # https://github.com/CircleCI-Public/cimg-base
      - image: cimg/base:current

jobs:
  test:
    docker:
      - image: hillliu/terratest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: "Test with terratest"
          command: |
            go test -timeout 30m -v ./tests | tee test_output.log
            terratest_log_parser -testlog test_output.log -outputdir test_output
      - store_test_results:
          path: test_output
  build-and-publish:
    parameters:
      docker-tag:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Log time
          command: date
      - run:
          name: Gen Docker file
          command: |
            VER_PREFIX=$(support/VER_PREFIX.sh)
            DOCKER_FILES=$(support/DOCKER_FILES.sh)
            BUILD_FOLDER=${VER_PREFIX}-<< parameters.docker-tag >>
            ./support/build-multi.sh << parameters.docker-tag >>
            ls -la ${BUILD_FOLDER}
            for file in $DOCKER_FILES; do
              echo ""
              echo "###"
              echo "# --- Dockerfile ($file) Content ---"
              echo "###"
              echo ""
              cat ${BUILD_FOLDER}/$file
              echo ""
            done
      - run:
          name: build Docker image
          command: |
            VER_PREFIX=$(support/VER_PREFIX.sh)
            IMAGE_NAME=$(DOCKER_HUB=1 support/remoteImage.sh)
            BUILD_VERSION=<< parameters.docker-tag >>
            BUILD_FOLDER=${VER_PREFIX}-<< parameters.docker-tag >>
            BUILD_ARG=""
            docker build ${BUILD_ARG} -f ${BUILD_FOLDER}/Dockerfile \
              -t $IMAGE_NAME:${BUILD_VERSION} \
              ./${BUILD_FOLDER}
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            DOCKER_HUB=1 ./compile.sh p << parameters.docker-tag >>

workflows:
  run-job:
    jobs:
      - test
      - build-and-publish:
          requires:
            - test
          matrix:
            parameters:
              docker-tag: ["0.4.25"]
