version: 2.1

commands:
  install-docker-buildx:
    description: Install Docker Buildx
    steps:
      - run:
          name: Install Docker Buildx
          command: |
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L "https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
            sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
            docker run --rm --privileged tonistiigi/binfmt --install arm64
            docker context create buildcontext
            docker buildx create buildcontext --use

executors:
  docker-publisher:
    docker:
      # https://github.com/CircleCI-Public/cimg-base
      - image: cimg/base:current

jobs:
  test:
    docker:
      - image: allfunc/terratest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run:
          name: "Test with terratest"
          command: |
            go test -timeout 30m -v ./tests | tee test_output.log
            terratest_log_parser -testlog test_output.log -outputdir test_output
      - store_test_results:
          path: test_output
  build-and-publish:
    parameters:
      docker-tag:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run:
          name: Log time
          command: date
      - run:
          name: Gen Docker file
          command: |
            VER_PREFIX=$(support/VER_PREFIX.sh)
            DOCKER_FILES=$(support/DOCKER_FILES.sh)
            BUILD_FOLDER=${VER_PREFIX}-<< parameters.docker-tag >>
            ./support/build-multi.sh << parameters.docker-tag >>
            ls -la ${BUILD_FOLDER}
            for file in $DOCKER_FILES; do
              echo ""
              echo "###"
              echo "# --- Dockerfile ($file) Content ---"
              echo "###"
              echo ""
              cat ${BUILD_FOLDER}/$file
              echo ""
            done
      - install-docker-buildx
      - run:
          name: login
          command: ./compile.sh login
      - run:
          name: build Docker image
          command: |
            VER_PREFIX=$(support/VER_PREFIX.sh)
            VERSION=$(support/VERSION.sh)
            ALT_VERSION=$(support/ALT_VERSION.sh)
            IMAGE_NAME=$(DOCKER_HUB=1 support/remoteImage.sh)
            BUILD_VERSION=<< parameters.docker-tag >>
            BUILD_FOLDER=${VER_PREFIX}-<< parameters.docker-tag >>
            BUILD_ARG=""
            LATEST_TAG=""
            if [ "x$VERSION" == "x$BUILD_VERSION" ]; then
                if [ -n "${ALT_VERSION}" ]; then
                  BUILD_ARG="--build-arg ALT_VERSION=${ALT_VERSION}"
                fi
                LATEST_TAG="-t $IMAGE_NAME:latest"
            fi
            echo "Build ARGS: ${BUILD_ARG}"
            docker buildx inspect --bootstrap
            docker buildx build ${BUILD_ARG} -f ${BUILD_FOLDER}/Dockerfile \
              --push \
              --platform linux/amd64,linux/arm64/v8 \
              -t $IMAGE_NAME:${BUILD_VERSION} ${LATEST_TAG} \
              ./${BUILD_FOLDER}
      - run:
          name: logout 
          command: docker logout

workflows:
  run-job:
    jobs:
      - test
      - build-and-publish:
          requires:
            - test
          matrix:
            parameters:
              docker-tag: ["0.4.30"]
