[book]
authors = []
language = "en"
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.plantuml]
plantuml-cmd="java -jar /app/plantuml.jar"

[output.html]
mathjax-support = true
additional-css = ["assets/mermaid.css", "assets/print.css"]
additional-js = ["assets/mermaid.min.js", "assets/import-html.js"]

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
